import React from "react";
import ScrollToDiv from "../utils/ScrollToDiv";

const Disability = () => {
  return (
    <>
      <ScrollToDiv targetDiv=".hero-container" />
      <div className="hero-container full-width-container">
        <div className="hero-content">
          <h1 className="light hero-title">DD</h1>
          <h2 className="light">Developmental Disabilities</h2>
          <h3 className="light">Client Management Solutions</h3>
        </div>
      </div>

      <div className="pages-container">
        <section>
          <h2 className="dark">Why EDORA?</h2>
          <div className="text-block">
            In a world where individuals with developmental disabilities and
            delays deserve every opportunity to thrive, <strong>EDORA</strong>{" "}
            is designed to transform how the DD interacts with clients and
            families, ensuring that services are accessible, tailored, and
            efficient.
            <p>
              <strong>EDORA</strong> stands at the forefront of disability
              services management, revolutionizing how individuals with
              developmental disabilities and their families access, coordinate,
              and manage care. By integrating comprehensive service offerings
              with an intuitive interface, EDORA empowers users to make informed
              choices and fosters a supportive community.
            </p>
          </div>
          <h3 className="dark">Seamless Data Capture</h3>
          <div className="text-block">
            EDORA integrates advanced data collection techniques, ensuring that
            all client interactions, service utilizations, and progress metrics
            are accurately recorded in real-time. This means that program
            managers have immediate access to comprehensive data that reflects
            current trends and needs within the community.
          </div>

          <h3 className="dark">Enhanced Reporting Capabilities</h3>
          <div className="text-block">
            The data-driven insights generated by EDORA allow program managers
            to quickly assess service effectiveness, identify gaps, and make
            informed decisions. Customizable reports provide a clear view of
            resource allocation and program outcomes, fostering a culture of
            accountability and transparency.
          </div>

          <h3 className="dark">Proactive Management Tools</h3>
          <div className="text-block">
            With EDORA's case management tools, program managers can proactively
            track appointments, monitor client progress, and communicate
            efficiently with service providers and families. This streamlined
            approach not only reduces administrative burdens but also enhances
            the overall service delivery process.
          </div>

          <h3 className="dark">Tailored Support</h3>
          <div className="text-block">
            EDORA's capacity for personalized data analysis ensures that program
            managers can identify specific client needs and adapt services
            accordingly. This adaptability promotes better outcomes and client
            satisfaction, reassuring families that their loved ones are
            receiving the highest quality of care.
          </div>

          <h2 class="dark">Key Features</h2>

          <dl>
            <dt>Intuitive User Interface</dt>
            <dd>
              EDORA features a user-friendly interface designed for all users,
              simplifying the process of finding and accessing services.
            </dd>

            <dt>Comprehensive Service Directory</dt>
            <dd>
              Users can easily access a detailed directory of services available
              for infants and toddlers, including developmental screenings,
              therapies, and care plans.
            </dd>

            <dt>Personalized Care Plans</dt>
            <dd>
              Families can collaborate with service providers to create and
              manage individualized care plans tailored to their loved ones'
              unique needs.
            </dd>

            <dt>Case Management Tools</dt>
            <dd>
              Comprehensive tools enable tracking of progress, appointment
              management, and effective communication.
            </dd>

            <dt>Referral and Intake Management</dt>
            <dd>
              Seamless integration for initiating service requests, allowing
              clients to contact DDS directly.
            </dd>

            <dt>Resource Library</dt>
            <dd>
              A comprehensive library of resources empowering families with
              knowledge and guidance.
            </dd>

            <dt>Data-Driven Insights</dt>
            <dd>
              Leveraging analytics to provide insights into service utilization
              and trends.
            </dd>

            <dt>Community Engagement</dt>
            <dd>
              Connecting users with local support groups, workshops, and events
              to foster community involvement.
            </dd>

            <dt>Accessibility Features</dt>
            <dd>
              Designed to ensure usability for all individuals, regardless of
              abilities.
            </dd>
          </dl>
          </section>
      </div>
    </>
  );
};

export default Disability;
