import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import axios from "axios";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

import allServices from "../../../data/hhsServices";

import ScrollToDiv from "../../../utils/ScrollToDiv";
import HelpDescription from "./helpDescription";
import ProgressBar from "./ProgresBar";

import "./styles/CaseStoryPage.css";

const CaseStoryPage = () => {
  const [selectedDivision, setSelectedDivision] = useState("");
  const [selectedTitle, setSelectedTitle] = useState("");
  const [description, setDescription] = useState("");
  const [selectedOption, setSelectedOption] = useState("");
  const [selectedServices, setSelectedServices] = useState([]);
  const [nextInput, setNextInput] = useState("");
  const [currentStep, setCurrentStep] = useState(0);

  // Separate search terms for each listbox
  const [searchTermDivision, setSearchTermDivision] = useState("");
  const [searchTermTitle, setSearchTermTitle] = useState("");
  const [searchTermOption, setSearchTermOption] = useState("");
  const [charCount, setCharCount] = useState(0);

  const fetchCaseDetails = async (division) => {
    try {
      const response = await axios.get(
        `https://api.example.com/cases?division=${division}`
      );
      const caseDetails = response.data;

      // Use the fetched data to auto-fill relevant fields
      setSelectedTitle(caseDetails.title || "");
      setDescription(caseDetails.description || "");
      setSelectedOption(caseDetails.defaultOption || "");
    } catch (error) {
      console.error("Error fetching case details:", error);
    }
  };

  const handleExportPDF = () => {
    const input = document.getElementById("client-journey");

    // Add the PDF-specific class to ensure formatting is clean
    input.classList.add("pdf-content");

    html2canvas(input)
      .then((canvas) => {
        const imgData = canvas.toDataURL("image/png");
        const pdf = new jsPDF("p", "mm", "a4");

        // Add Header
        pdf.setFontSize(18);
        pdf.setFont("helvetica", "bold");
        pdf.text("Client Journey Report", 105, 20, { align: "center" });

        pdf.setFontSize(12);
        pdf.setFont("helvetica", "normal");
        pdf.text("Generated by EDORA", 105, 28, { align: "center" });

        // Add some padding before the main content
        const startY = 40;

        // Calculate image size to fit in A4
        const imgWidth = 190; // A4 width in mm, with some padding
        const imgHeight = (canvas.height * imgWidth) / canvas.width;

        // Add the image content (captured HTML element)
        pdf.addImage(imgData, "PNG", 10, startY, imgWidth, imgHeight);

        // Add Footer
        const pageHeight = pdf.internal.pageSize.height;
        pdf.setFontSize(10);
        pdf.text(
          "This document is confidential and intended for internal use only.",
          105,
          pageHeight - 10,
          { align: "center" }
        );

        // Save the PDF
        pdf.save("client-journey.pdf");

        // Remove the PDF-specific class after generating the PDF to revert styles
        input.classList.remove("pdf-content");
      })
      .catch((error) => {
        console.error("Could not generate PDF", error);
        // Remove the PDF-specific class even if there's an error
        input.classList.remove("pdf-content");
      });
    const totalPages = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(10);
      pdf.text(`Page ${i} of ${totalPages}`, 105, pageHeight - 5, {
        align: "center",
      });
    }
  };

  // Update the step as users make selections
  useEffect(() => {
    let step = 0;
    if (selectedDivision) step += 1;
    if (selectedTitle) step += 1;
    if (selectedOption || !selectedService?.options?.length) step += 1;
    setCurrentStep(step);
  }, [selectedDivision, selectedTitle, selectedOption]);

  const handleDivisionChange = (division) => {
    setSelectedDivision(division);
    setSelectedTitle("");
    setDescription("");
    setSelectedOption("");
    setNextInput("");
    setSearchTermDivision(""); // Reset search term when selecting a division

    if (division) {
      fetchCaseDetails(division); // Fetch and auto-fill data
    }
  };

  const handleTitleChange = (title) => {
    const service = allServices.find(
      (service) =>
        service.title === title && service.division === selectedDivision
    );

    if (service) {
      setSelectedTitle(title);
      setDescription(service.description);
      setSelectedOption("");
      setNextInput("");
      setSearchTermTitle(""); // Reset search term when selecting a title
    }
  };

  const handleOptionChange = (option) => {
    setSelectedOption(option);
    const selected = selectedService?.options.find(
      (opt) => opt.next === option
    );
    setNextInput(selected ? "" : nextInput);
    setSearchTermOption(""); // Reset search term when selecting an option
  };

  // const handleNextInputChange = (event) => {
  //   setNextInput(event.target.value);
  // };

  // Update character count as user types

  const handleNextInputChange = (event) => {
    setNextInput(event.target.value);
    setCharCount(event.target.value.length);
  };

  const handleAddService = () => {
    const newService = {
      division: selectedDivision,
      title: selectedTitle,
      option: selectedOption || "No extra option",
      nextInput: nextInput || "", // Include "What's Next" input
    };
    setSelectedServices((prevServices) => [...prevServices, newService]);

    // Reset the fields after adding
    setSelectedDivision("");
    setSelectedTitle("");
    setSelectedOption("");
    setNextInput("");

    // Reset the search filters too
    setSearchTermDivision("");
    setSearchTermTitle("");
    setSearchTermOption("");
  };

  const divisions = [
    ...new Set(allServices.map((service) => service.division)),
  ];
  const filteredServices = allServices.filter(
    (service) => service.division === selectedDivision
  );
  const selectedService = allServices.find(
    (service) => service.title === selectedTitle
  );

  return (
    <div className="pages-container">
      <ScrollToDiv targetDiv=".top" />
      <div className="case-story-page">
        <h3 className="dark header-title">Bring Your Client's Story to Life</h3>

        {/* Help Description Component */}
        <HelpDescription />
        <ProgressBar currentStep={currentStep} totalSteps={3} />

        {/* Listboxes Container */}
        <div className="listboxes-container">
          {/* Division Selector */}
          <div className="selector division-selector">
            <label htmlFor="division" className="label">
              Select Division:
            </label>
            <input
              type="text"
              value={searchTermDivision}
              onChange={(e) => setSearchTermDivision(e.target.value)}
              placeholder="Search divisions..."
              className="search-box"
            />
            <div className="list-box">
              <motion.div
                className="list-item"
                onClick={() => handleDivisionChange("")}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
              >
                --Choose Division--
              </motion.div>
              {divisions
                .filter((division) =>
                  division
                    .toLowerCase()
                    .includes(searchTermDivision.toLowerCase())
                )
                .map((division, index) => (
                  <motion.div
                    key={index}
                    className={`list-item ${
                      selectedDivision === division ? "selected" : ""
                    }`}
                    onClick={() => handleDivisionChange(division)}
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ duration: 0.5 }}
                  >
                    {division}
                  </motion.div>
                ))}
            </div>
          </div>

          {/* Title Selector */}
          {selectedDivision && (
            <div className="selector title-selector">
              <label htmlFor="title" className="label">
                Select Event:
              </label>
              <input
                type="text"
                value={searchTermTitle}
                onChange={(e) => setSearchTermTitle(e.target.value)}
                placeholder="Search events..."
                className="search-box"
              />
              <div className="list-box">
                <div
                  className="list-item"
                  onClick={() => handleTitleChange("")}
                >
                  --Choose Title--
                </div>
                {filteredServices
                  .filter((service) =>
                    service.title
                      .toLowerCase()
                      .includes(searchTermTitle.toLowerCase())
                  )
                  .map((service) => (
                    <div
                      key={service.id}
                      className={`list-item ${
                        selectedTitle === service.title ? "selected" : ""
                      }`}
                      onClick={() => handleTitleChange(service.title)}
                    >
                      {service.title}
                    </div>
                  ))}
              </div>
            </div>
          )}

          {/* Options Selector */}
          {selectedService && selectedService.options.length > 0 && (
            <div className="selector options-selector">
              <label htmlFor="options" className="label">
                Select Additional Event Option:
              </label>
              <input
                type="text"
                value={searchTermOption}
                onChange={(e) => setSearchTermOption(e.target.value)}
                placeholder="Search options..."
                className="search-box"
              />
              <div className="list-box">
                <div
                  className="list-item"
                  onClick={() => handleOptionChange("")}
                >
                  --Choose Option--
                </div>
                {selectedService.options
                  .filter((option) =>
                    option.label
                      .toLowerCase()
                      .includes(searchTermOption.toLowerCase())
                  )
                  .map((option, index) => (
                    <div
                      key={index}
                      className={`list-item ${
                        selectedOption === option.next ? "selected" : ""
                      }`}
                      onClick={() => handleOptionChange(option.next)}
                    >
                      {option.label}
                    </div>
                  ))}
              </div>
            </div>
          )}
        </div>
        {(selectedDivision || selectedTitle || selectedOption) && (
          <div className="selected-overview">
            <h2 className="subheader">Your Selections:</h2>
            <ul className="selection-list">
              {selectedDivision && (
                <li>
                  <strong>Division:</strong> {selectedDivision}
                </li>
              )}
              {selectedTitle && (
                <li>
                  <strong>Event:</strong> {selectedTitle}
                </li>
              )}
              {selectedOption && (
                <li>
                  <strong>Operation:</strong> {selectedOption}
                </li>
              )}
            </ul>
          </div>
        )}
        {/* Description, Next Steps Input, Add Service Button */}
        {description && (
          <motion.div
            className="service-description"
            initial={{ x: -100, opacity: 0 }}
            animate={{ x: 0, opacity: 1 }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="subheader">Description:</h2>
            <p className="description-text">{description}</p>
          </motion.div>
        )}

        {selectedOption &&
          selectedService.options.some(
            (option) => option.next === selectedOption
          ) && (
            <div className="next-input">
              <label htmlFor="nextInput" className="label">
                What's next for the client?
              </label>
              <textarea
                id="nextInput"
                className="textbox"
                placeholder="Notes ..."
                value={nextInput}
                onChange={handleNextInputChange}
              />
              <p className="char-count">{charCount} / 500 characters</p>
            </div>
          )}

        {selectedTitle && (
          <div className="add-service-button">
            <button className="btn" onClick={handleAddService}>
              Add Service
            </button>
          </div>
        )}

        {selectedServices.length > 0 && (
          <div id="client-journey" className="selected-services-list">
            <h2 className="subheader">Client Journey with EDORA</h2>
            <ul>
              {selectedServices.map((service, index) => (
                <li key={index}>
                  {service.division} - {service.title}{" "}
                  {service.option !== "No extra option" &&
                    `(${service.option})`}
                  {service.nextInput &&
                    service.nextInput !== "" &&
                    ` - Next: ${service.nextInput}`}
                </li>
              ))}
            </ul>
          </div>
        )}
        {selectedServices.length > 0 && (
          <div className="export-button">
            <button className="btn" onClick={handleExportPDF}>
              Export PDF
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default CaseStoryPage;
